# Generated by Django 3.1.7 on 2021-05-14 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='image',
            field=models.ImageField(upload_to='gallery'),
        ),
    ]
