# Generated by Django 3.1.7 on 2021-05-15 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markers', '0002_auto_20210514_1837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='image',
        ),
    ]
